<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet metadata -->
    <PackageId>StrongTypedCache.InMemory</PackageId>
    <Version>1.1.0</Version>
    <Authors>KotBehamot</Authors>
    <Description>In-memory strongly-typed cache implementation.</Description>
    <RepositoryUrl>https://github.com/KotBehamot/strong-typed-cache</RepositoryUrl>
    <PackageTags>cache;in-memory;strongly-typed;dotnet</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StrongTypedCache.Abstractions\StrongTypedCache.Abstractions.csproj" />
  </ItemGroup>

</Project>
